In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df_1 = pd.read_csv("./best_model_experiment/experiments_v1/summary.csv").drop("run_id", axis=1)
df_2 = pd.read_csv("./best_model_experiment/experiments_v2/summary.csv").drop("run_id", axis=1)

for col in ["pr_auc", "recall_anomaly", "precision_anomaly", "f1_anomaly", "accuracy"]:
    if col in df_1.columns:
        df_1[col] = pd.to_numeric(df_1[col], errors="coerce")
        df_2[col] = pd.to_numeric(df_2[col], errors="coerce")

df_1

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
0,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.412067,0.000000,0.0,0.000000,0.950000,285,0,15,0
1,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.158193,0.000000,0.0,0.000000,0.950000,285,0,15,0
2,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.266851,0.000000,0.0,0.000000,0.950000,285,0,15,0
3,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.255740,0.000000,0.0,0.000000,0.950000,285,0,15,0
4,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.113739,0.000000,0.0,0.000000,0.950000,285,0,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.832332,0.666667,1.0,0.800000,0.983333,285,0,5,10
276,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.691979,0.400000,1.0,0.571429,0.970000,285,0,9,6
277,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.721663,0.066667,1.0,0.125000,0.953333,285,0,14,1
278,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.817017,0.466667,1.0,0.636364,0.973333,285,0,8,7
279,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.935892,0.600000,1.0,0.750000,0.980000,285,0,6,9

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
0,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.412067,0.000000,0.0,0.000000,0.950000,285,0,15,0
1,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.158193,0.000000,0.0,0.000000,0.950000,285,0,15,0
2,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.266851,0.000000,0.0,0.000000,0.950000,285,0,15,0
3,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.255740,0.000000,0.0,0.000000,0.950000,285,0,15,0
4,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.113739,0.000000,0.0,0.000000,0.950000,285,0,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.832332,0.666667,1.0,0.800000,0.983333,285,0,5,10
276,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.691979,0.400000,1.0,0.571429,0.970000,285,0,9,6
277,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.721663,0.066667,1.0,0.125000,0.953333,285,0,14,1
278,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.817017,0.466667,1.0,0.636364,0.973333,285,0,8,7
279,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.935892,0.600000,1.0,0.750000,0.980000,285,0,6,9

In [2]:
df_2.columns

Index(['sweep_key', 'sweep_value', 'feature_map', 'ansatz', 'ansatz_depth',
       'optimizer', 'seed', 'n_samples', 'anomaly_ratio', 'label_noise',
       'pr_auc', 'recall_anomaly', 'precision_anomaly', 'f1_anomaly',
       'accuracy', 'tn', 'fp', 'fn', 'tp'],
      dtype='object')

Index(['sweep_key', 'sweep_value', 'feature_map', 'ansatz', 'ansatz_depth',
       'optimizer', 'seed', 'n_samples', 'anomaly_ratio', 'label_noise',
       'pr_auc', 'recall_anomaly', 'precision_anomaly', 'f1_anomaly',
       'accuracy', 'tn', 'fp', 'fn', 'tp'],
      dtype='object')

In [3]:
df_2

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
0,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.131533,0.000000,0.000000,0.000000,0.906667,272,0,28,0
1,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.079074,0.000000,0.000000,0.000000,0.906667,272,0,28,0
2,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.117795,0.000000,0.000000,0.000000,0.903333,271,0,29,0
3,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.198373,0.000000,0.000000,0.000000,0.906667,272,0,28,0
4,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.080495,0.000000,0.000000,0.000000,0.903333,271,0,29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.562734,0.392857,0.916667,0.550000,0.940000,271,1,17,11
226,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.229023,0.142857,0.571429,0.228571,0.910000,269,3,24,4
227,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.471936,0.310345,1.000000,0.473684,0.933333,271,0,20,9
228,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.377940,0.214286,0.857143,0.342857,0.923333,271,1,22,6
229,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.253230,0.137931,0.800000,0.235294,0.913333,270,1,25,4

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
0,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.131533,0.000000,0.000000,0.000000,0.906667,272,0,28,0
1,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.079074,0.000000,0.000000,0.000000,0.906667,272,0,28,0
2,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.117795,0.000000,0.000000,0.000000,0.903333,271,0,29,0
3,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.198373,0.000000,0.000000,0.000000,0.906667,272,0,28,0
4,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.080495,0.000000,0.000000,0.000000,0.903333,271,0,29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.562734,0.392857,0.916667,0.550000,0.940000,271,1,17,11
226,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.229023,0.142857,0.571429,0.228571,0.910000,269,3,24,4
227,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.471936,0.310345,1.000000,0.473684,0.933333,271,0,20,9
228,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.377940,0.214286,0.857143,0.342857,0.923333,271,1,22,6
229,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.253230,0.137931,0.800000,0.235294,0.913333,270,1,25,4

In [4]:
agg_1 = (
    df_1.groupby(["sweep_key", "sweep_value"], as_index=False)
        .agg(
          pr_auc_mean=("pr_auc", "mean"),
          pr_auc_std=("pr_auc", "std"),
          recall_mean=("recall_anomaly", "mean"),
          recall_std=("recall_anomaly", "std"),
          f1_mean=("f1_anomaly", "mean"),
          f1_std=("f1_anomaly", "std"),
      )
)
agg_2 = (
    df_2.groupby(["sweep_key", "sweep_value"], as_index=False)
        .agg(
          pr_auc_mean=("pr_auc", "mean"),
          pr_auc_std=("pr_auc", "std"),
          recall_mean=("recall_anomaly", "mean"),
          recall_std=("recall_anomaly", "std"),
          f1_mean=("f1_anomaly", "mean"),
          f1_std=("f1_anomaly", "std"),
      )
)

agg_1 = agg_1.sort_values(["sweep_key", "sweep_value"])
agg_2 = agg_2.sort_values(["sweep_key", "sweep_value"])
agg_1

,sweep_key,sweep_value,pr_auc_mean,pr_auc_std,recall_mean,recall_std,f1_mean,f1_std
0,ansatz,real_amplitudes,0.816191,0.094539,0.480000,0.233333,0.603286,0.258516
1,ansatz,two_local,0.818150,0.121742,0.573333,0.054433,0.721594,0.048557
2,ansatz_depth,1,0.730692,0.055209,0.493333,0.180534,0.613891,0.137195
3,ansatz_depth,2,0.799776,0.088514,0.440000,0.213437,0.576558,0.244743
4,ansatz_depth,3,0.891119,0.050758,0.573333,0.110554,0.716647,0.090628
5,ansatz_depth,4,0.903436,0.038809,0.733333,0.105409,0.842723,0.070597
6,feature_map,pauli_feature_map,0.241318,0.105279,0.000000,0.000000,0.000000,0.000000
7,feature_map,z_feature_map,0.814998,0.097870,0.453333,0.229331,0.579000,0.254264
8,feature_map,zz_feature_map,0.091838,0.031749,0.173333,0.126198,0.109371,0.063853
9,optimizer,adam,0.810455,0.098644,0.453333,0.229331,0.579000,0.254264
10,optimizer,cobyla,0.836745,0.049104,0.493333,0.190516,0.640249,0.168125
11,optimizer,spsa,0.772913,0.132381,0.480000,0.145297,0.627749,0.150534

,sweep_key,sweep_value,pr_auc_mean,pr_auc_std,recall_mean,recall_std,f1_mean,f1_std
0,ansatz,real_amplitudes,0.816191,0.094539,0.480000,0.233333,0.603286,0.258516
1,ansatz,two_local,0.818150,0.121742,0.573333,0.054433,0.721594,0.048557
2,ansatz_depth,1,0.730692,0.055209,0.493333,0.180534,0.613891,0.137195
3,ansatz_depth,2,0.799776,0.088514,0.440000,0.213437,0.576558,0.244743
4,ansatz_depth,3,0.891119,0.050758,0.573333,0.110554,0.716647,0.090628
5,ansatz_depth,4,0.903436,0.038809,0.733333,0.105409,0.842723,0.070597
6,feature_map,pauli_feature_map,0.241318,0.105279,0.000000,0.000000,0.000000,0.000000
7,feature_map,z_feature_map,0.814998,0.097870,0.453333,0.229331,0.579000,0.254264
8,feature_map,zz_feature_map,0.091838,0.031749,0.173333,0.126198,0.109371,0.063853
9,optimizer,adam,0.810455,0.098644,0.453333,0.229331,0.579000,0.254264
10,optimizer,cobyla,0.836745,0.049104,0.493333,0.190516,0.640249,0.168125
11,optimizer,spsa,0.772913,0.132381,0.480000,0.145297,0.627749,0.150534

In [5]:
agg_2

,sweep_key,sweep_value,pr_auc_mean,pr_auc_std,recall_mean,recall_std,f1_mean,f1_std
0,ansatz,real_amplitudes,0.386423,0.124647,0.239655,0.101389,0.366081,0.131356
1,ansatz,two_local,0.166526,0.046247,0.084483,0.037154,0.126020,0.052916
2,ansatz_depth,1,0.210241,0.030698,0.253202,0.098147,0.238181,0.067610
3,ansatz_depth,2,0.378973,0.130350,0.239655,0.101389,0.366081,0.131356
4,ansatz_depth,3,0.311185,0.072446,0.147783,0.048080,0.239756,0.076506
5,ansatz_depth,4,0.390215,0.090294,0.189409,0.081062,0.309405,0.114874
6,feature_map,pauli_feature_map,0.121454,0.044733,0.000000,0.000000,0.000000,0.000000
7,feature_map,z_feature_map,0.377944,0.131049,0.239655,0.101389,0.366081,0.131356
8,feature_map,zz_feature_map,0.161936,0.040377,0.211084,0.058547,0.164398,0.033806
9,optimizer,adam,0.382552,0.127864,0.232512,0.104289,0.356333,0.134652
10,optimizer,cobyla,0.408715,0.115618,0.232266,0.117784,0.360193,0.154192
11,optimizer,spsa,0.199838,0.145121,0.104433,0.111727,0.154329,0.171940

,sweep_key,sweep_value,pr_auc_mean,pr_auc_std,recall_mean,recall_std,f1_mean,f1_std
0,ansatz,real_amplitudes,0.386423,0.124647,0.239655,0.101389,0.366081,0.131356
1,ansatz,two_local,0.166526,0.046247,0.084483,0.037154,0.126020,0.052916
2,ansatz_depth,1,0.210241,0.030698,0.253202,0.098147,0.238181,0.067610
3,ansatz_depth,2,0.378973,0.130350,0.239655,0.101389,0.366081,0.131356
4,ansatz_depth,3,0.311185,0.072446,0.147783,0.048080,0.239756,0.076506
5,ansatz_depth,4,0.390215,0.090294,0.189409,0.081062,0.309405,0.114874
6,feature_map,pauli_feature_map,0.121454,0.044733,0.000000,0.000000,0.000000,0.000000
7,feature_map,z_feature_map,0.377944,0.131049,0.239655,0.101389,0.366081,0.131356
8,feature_map,zz_feature_map,0.161936,0.040377,0.211084,0.058547,0.164398,0.033806
9,optimizer,adam,0.382552,0.127864,0.232512,0.104289,0.356333,0.134652
10,optimizer,cobyla,0.408715,0.115618,0.232266,0.117784,0.360193,0.154192
11,optimizer,spsa,0.199838,0.145121,0.104433,0.111727,0.154329,0.171940

In [6]:
group_cols = [
    "sweep_key",
    "sweep_value",
    "feature_map",
    "ansatz",
    "ansatz_depth",
    "optimizer",
    "n_samples",
    "anomaly_ratio",
    "label_noise"
]

metric_cols = [
    "pr_auc",
    "recall_anomaly",
    "precision_anomaly",
    "f1_anomaly",
    "accuracy",
    "tn",
    "fp",
    "fn",
    "tp"
]

df_avg = (
    df_2.groupby(group_cols)[metric_cols]
    .mean()
    .reset_index()
)

df_avg["seed"] = "avg"

df_2 = pd.concat([df_2, df_avg], ignore_index=True)

In [7]:
df_2[df_2["seed"] == "avg"]

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
230,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.386423,0.239655,0.829048,0.366081,0.924000,270.4,1.2,21.6,6.8
231,ansatz,two_local,z_feature_map,two_local,2,adam,avg,1000,0.05,0.05,0.166526,0.084483,0.272222,0.126020,0.890667,264.8,6.8,26.0,2.4
232,ansatz_depth,1,z_feature_map,real_amplitudes,1,adam,avg,1000,0.05,0.05,0.210241,0.253202,0.239645,0.238181,0.851333,248.2,23.4,21.2,7.2
233,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.378973,0.239655,0.829048,0.366081,0.924000,270.4,1.2,21.6,6.8
234,ansatz_depth,3,z_feature_map,real_amplitudes,3,adam,avg,1000,0.05,0.05,0.311185,0.147783,0.824762,0.239756,0.911333,269.2,2.4,24.2,4.2
235,ansatz_depth,4,z_feature_map,real_amplitudes,4,adam,avg,1000,0.05,0.05,0.390215,0.189409,0.971429,0.309405,0.922667,271.4,0.2,23.0,5.4
236,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.121454,0.000000,0.000000,0.000000,0.905333,271.6,0.0,28.4,0.0
237,feature_map,z_feature_map,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.377944,0.239655,0.829048,0.366081,0.924000,270.4,1.2,21.6,6.8
238,feature_map,zz_feature_map,zz_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.161936,0.211084,0.137211,0.164398,0.798667,233.6,38.0,22.4,6.0
239,optimizer,adam,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.382552,0.232512,0.824286,0.356333,0.923333,270.4,1.2,21.8,6.6
240,optimizer,cobyla,z_feature_map,real_amplitudes,2,cobyla,avg,1000,0.05,0.05,0.408715,0.232266,0.916667,0.360193,0.926000,271.2,0.4,21.8,6.6
241,optimizer,spsa,z_feature_map,real_amplitudes,2,spsa,avg,1000,0.05,0.05,0.199838,0.104433,0.319048,0.154329,0.875333,259.6,12.0,25.4,3.0

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
230,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.386423,0.239655,0.829048,0.366081,0.924000,270.4,1.2,21.6,6.8
231,ansatz,two_local,z_feature_map,two_local,2,adam,avg,1000,0.05,0.05,0.166526,0.084483,0.272222,0.126020,0.890667,264.8,6.8,26.0,2.4
232,ansatz_depth,1,z_feature_map,real_amplitudes,1,adam,avg,1000,0.05,0.05,0.210241,0.253202,0.239645,0.238181,0.851333,248.2,23.4,21.2,7.2
233,ansatz_depth,2,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.378973,0.239655,0.829048,0.366081,0.924000,270.4,1.2,21.6,6.8
234,ansatz_depth,3,z_feature_map,real_amplitudes,3,adam,avg,1000,0.05,0.05,0.311185,0.147783,0.824762,0.239756,0.911333,269.2,2.4,24.2,4.2
235,ansatz_depth,4,z_feature_map,real_amplitudes,4,adam,avg,1000,0.05,0.05,0.390215,0.189409,0.971429,0.309405,0.922667,271.4,0.2,23.0,5.4
236,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.121454,0.000000,0.000000,0.000000,0.905333,271.6,0.0,28.4,0.0
237,feature_map,z_feature_map,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.377944,0.239655,0.829048,0.366081,0.924000,270.4,1.2,21.6,6.8
238,feature_map,zz_feature_map,zz_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.161936,0.211084,0.137211,0.164398,0.798667,233.6,38.0,22.4,6.0
239,optimizer,adam,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.382552,0.232512,0.824286,0.356333,0.923333,270.4,1.2,21.8,6.6
240,optimizer,cobyla,z_feature_map,real_amplitudes,2,cobyla,avg,1000,0.05,0.05,0.408715,0.232266,0.916667,0.360193,0.926000,271.2,0.4,21.8,6.6
241,optimizer,spsa,z_feature_map,real_amplitudes,2,spsa,avg,1000,0.05,0.05,0.199838,0.104433,0.319048,0.154329,0.875333,259.6,12.0,25.4,3.0

In [8]:
df_2["seed"] = df_2["seed"].astype(str)
df_2.to_excel("agg2_bm.xlsx", index=False)

In [9]:
df_2.shape

(242, 19)

(242, 19)

In [10]:
df_2

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
0,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.131533,0.000000,0.000000,0.000000,0.906667,272.0,0.0,28.0,0.0
1,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.079074,0.000000,0.000000,0.000000,0.906667,272.0,0.0,28.0,0.0
2,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.117795,0.000000,0.000000,0.000000,0.903333,271.0,0.0,29.0,0.0
3,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.198373,0.000000,0.000000,0.000000,0.906667,272.0,0.0,28.0,0.0
4,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.080495,0.000000,0.000000,0.000000,0.903333,271.0,0.0,29.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,feature_map,z_feature_map,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.377944,0.239655,0.829048,0.366081,0.924000,270.4,1.2,21.6,6.8
238,feature_map,zz_feature_map,zz_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.161936,0.211084,0.137211,0.164398,0.798667,233.6,38.0,22.4,6.0
239,optimizer,adam,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.382552,0.232512,0.824286,0.356333,0.923333,270.4,1.2,21.8,6.6
240,optimizer,cobyla,z_feature_map,real_amplitudes,2,cobyla,avg,1000,0.05,0.05,0.408715,0.232266,0.916667,0.360193,0.926000,271.2,0.4,21.8,6.6
241,optimizer,spsa,z_feature_map,real_amplitudes,2,spsa,avg,1000,0.05,0.05,0.199838,0.104433,0.319048,0.154329,0.875333,259.6,12.0,25.4,3.0

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
0,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.131533,0.000000,0.000000,0.000000,0.906667,272.0,0.0,28.0,0.0
1,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,4,1000,0.05,0.05,0.079074,0.000000,0.000000,0.000000,0.906667,272.0,0.0,28.0,0.0
2,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,3,1000,0.05,0.05,0.117795,0.000000,0.000000,0.000000,0.903333,271.0,0.0,29.0,0.0
3,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,1,1000,0.05,0.05,0.198373,0.000000,0.000000,0.000000,0.906667,272.0,0.0,28.0,0.0
4,feature_map,pauli_feature_map,pauli_feature_map,real_amplitudes,2,adam,0,1000,0.05,0.05,0.080495,0.000000,0.000000,0.000000,0.903333,271.0,0.0,29.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,feature_map,z_feature_map,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.377944,0.239655,0.829048,0.366081,0.924000,270.4,1.2,21.6,6.8
238,feature_map,zz_feature_map,zz_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.161936,0.211084,0.137211,0.164398,0.798667,233.6,38.0,22.4,6.0
239,optimizer,adam,z_feature_map,real_amplitudes,2,adam,avg,1000,0.05,0.05,0.382552,0.232512,0.824286,0.356333,0.923333,270.4,1.2,21.8,6.6
240,optimizer,cobyla,z_feature_map,real_amplitudes,2,cobyla,avg,1000,0.05,0.05,0.408715,0.232266,0.916667,0.360193,0.926000,271.2,0.4,21.8,6.6
241,optimizer,spsa,z_feature_map,real_amplitudes,2,spsa,avg,1000,0.05,0.05,0.199838,0.104433,0.319048,0.154329,0.875333,259.6,12.0,25.4,3.0

In [11]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sweep_key          242 non-null    object
 1   sweep_value        242 non-null    object
 2   feature_map        242 non-null    object
 3   ansatz             242 non-null    object
 4   ansatz_depth       242 non-null    int64
 5   optimizer          242 non-null    object
 6   seed               242 non-null    object
 7   n_samples          242 non-null    int64
 8   anomaly_ratio      242 non-null    float64
 9   label_noise        242 non-null    float64
 10  pr_auc             242 non-null    float64
 11  recall_anomaly     242 non-null    float64
 12  precision_anomaly  242 non-null    float64
 13  f1_anomaly         242 non-null    float64
 14  accuracy           242 non-null    float64
 15  tn                 242 non-null    float64
 16  fp                 242 non-null    float64
 17  fn                 242 non-null    float64
 18  tp                 242 non-null    float64
dtypes: float64(11), int64(2), object(6)
memory usage: 36.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sweep_key          242 non-null    object
 1   sweep_value        242 non-null    object
 2   feature_map        242 non-null    object
 3   ansatz             242 non-null    object
 4   ansatz_depth       242 non-null    int64
 5   optimizer          242 non-null    object
 6   seed               242 non-null    object
 7   n_samples          242 non-null    int64
 8   anomaly_ratio      242 non-null    float64
 9   label_noise        242 non-null    float64
 10  pr_auc             242 non-null    float64
 11  recall_anomaly     242 non-null    float64
 12  precision_anomaly  242 non-null    float64
 13  f1_anomaly         242 non-null    float64
 14  accuracy           242 non-null    float64
 15  tn                 242 non-null    float64
 16  fp                 242 non-null    float64
 17  fn                 242 non-null    float64
 18  tp                 242 non-null    float64
dtypes: float64(11), int64(2), object(6)
memory usage: 36.0+ KB

In [12]:
df_2[(df_2["sweep_value"] == "real_amplitudes") & (df_2["seed"] == "2")]

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
15,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.566127,0.392857,0.916667,0.55,0.94,271.0,1.0,17.0,11.0
70,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.566127,0.392857,0.916667,0.55,0.94,271.0,1.0,17.0,11.0
125,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.566127,0.392857,0.916667,0.55,0.94,271.0,1.0,17.0,11.0
185,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.566127,0.392857,0.916667,0.55,0.94,271.0,1.0,17.0,11.0

,sweep_key,sweep_value,feature_map,ansatz,ansatz_depth,optimizer,seed,n_samples,anomaly_ratio,label_noise,pr_auc,recall_anomaly,precision_anomaly,f1_anomaly,accuracy,tn,fp,fn,tp
15,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.566127,0.392857,0.916667,0.55,0.94,271.0,1.0,17.0,11.0
70,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.566127,0.392857,0.916667,0.55,0.94,271.0,1.0,17.0,11.0
125,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.566127,0.392857,0.916667,0.55,0.94,271.0,1.0,17.0,11.0
185,ansatz,real_amplitudes,z_feature_map,real_amplitudes,2,adam,2,1000,0.05,0.05,0.566127,0.392857,0.916667,0.55,0.94,271.0,1.0,17.0,11.0